###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

disable_analytics: true
_site_url: http://localhost.statamechanic.com
